### ISSUE TITLE
Doesn't work with Game Pass

### ISSUE THREAD

**Issue by Kurasami** [p1xel8ted/UltrawideFixes#1]
![Screenshot_1](https://github.com/p1xel8ted/UltrawideFixes/assets/77334270/cf4254f5-5915-4844-8668-49bd4af56e2d)

Is there some other way to do this? Even running as administrator doesn't help.

**Comment by WillScarlettOhara** [comment]
Hi, choose gamelaunchhelper.exe instead ;)

**Comment by Kurasami** [comment]
Thanks it works! <3
