### ISSUE TITLE
Sea of Stars: UI Position

### ISSUE THREAD

**Issue by feeebl** [p1xel8ted/UltrawideFixes#10]
Hi,

First of all, thanks so much for your work!
When I opened Sea of Stars after I didn't play it for a while I noticed it wasn't running full widescreen anymore, but I did remember having installed this fix. So I reinstalled the fix, and then this issue popped up:

![image](https://github.com/p1xel8ted/UltrawideFixes/assets/150964813/a14d2cc0-d768-40fd-a2e4-7748e6d90881)
![image](https://github.com/p1xel8ted/UltrawideFixes/assets/150964813/c155d5f0-d0a1-4ae3-9282-372bca23c343)
![image](https://github.com/p1xel8ted/UltrawideFixes/assets/150964813/066e6b72-16ea-4c3f-b1b5-055aa6d8780d)

Already looked at the closed issues, particularly [this issue](https://github.com/p1xel8ted/UltrawideFixes/issues/3#issuecomment-1760043847) and you recommended reinstalling the mod completely and deleting the configuration file. Deleted the mod and all the other files extracted by the .zip of the fix, (what is the config file you're referencing?) Unfortunately the issue persists.

Resolution: 3440x1440
Gamepass version
Version 0.1.9 of the mod

Tried both installer and manual versions.

Thanks

**Comment by feeebl** [comment]
Reinstalling the entire game through gamepass (e.g. deleting the folder) then reinstalling and reinstalling the mod does not fix the problem.

**Comment by p1xel8ted** [comment]
Try 0.1.8

**Comment by feeebl** [comment]
Both 0.1.8 not pressing +-* works.

**Comment by malger** [comment]
have the same problem. + / - does not work. i have qwertz (10k-less) layout, maybe thats why?

**Comment by p1xel8ted** [comment]
@feeebl what resolution are you using

**Comment by p1xel8ted** [comment]
[SeaOfStarsUltraWide.zip](https://github.com/p1xel8ted/UltrawideFixes/files/13435773/SeaOfStarsUltraWide.zip)

LeftBracket [ = Move UI left
RightBracket ] = Move UI Right
Pipe\Backslash = Reset

Tested on GamePass and Steam @ 3440x1440 - autocalcs position fine and the moving left/right/reset works fine

**Comment by Ost3rbaer** [comment]
Thx a lot - this version now finally displays the UI at a usable position. Also movement of the UI works as you write.
However, one issue remains: the text  is scaled rather weird, it some strokes are wider than others - see attached screenshot:
![grafik](https://github.com/p1xel8ted/UltrawideFixes/assets/47357005/a61cd4bc-60e3-470d-8ed8-20dd008f3df3)

My resolution on the main screen is 3840x1600 (ratio 2.4, not 21:9).

**Comment by feeebl** [comment]
Thanks, that version also worked perfectly for me!
