### ISSUE TITLE
Crashes while testing of Prince of Persia Ubi+ version with ultrawide fix

### ISSUE THREAD

**Issue by Dorsman** [p1xel8ted/UltrawideFixes#14]
Just passing along my issues. I assume you already know about what happens with the map. I just wanted to say that I used the fix for 20 minutes on the Ubi+ version and I have already had two crashes to desktop so something seems unstable. Both times it crashes during gameplay.

**Comment by p1xel8ted** [comment]
@Dorsman leave BepInEx installed, but delete the fix from the plugins folder. See if it still ocurrs

**Comment by Dorsman** [comment]
@p1xel8ted Sorry if I am missing something but I deleted that file in BepInEx plugins folder (PrinceOfPersiaTheLostCrownUltrawide.dll) and now the game no longer gives me an ulrawide resolution option in the menu so it's back to black bars. Ubi also released a patch this morning so not sure if that messed anything up. If I put that .dll file back into the plugins folder my ultrawide resolution option returns.

**Comment by p1xel8ted** [comment]
That is correct - we need to determine if it's BepInEx itself or the plugin

**Comment by Dorsman** [comment]
OK I see. I will test tonight with just that file removed from the plugins folder and see if I get crashes.

**Comment by Dorsman** [comment]
@p1xel8ted OK I deleted the file from the plugins folder and played for an hour without crashes FYI.

**Comment by p1xel8ted** [comment]
@Dorsman Please remove all traces of BepInEx once more and use this version instead.

This will not work for the Retail version of the game.

https://github.com/p1xel8ted/UltrawideFixes/releases/download/PrinceOfPersiaTheLostCrown/01.1.PrinceOfPersia_v0.1.3_BepInEx-Ubisoft+ONLY.zip

**Comment by Dorsman** [comment]
@p1xel8ted I removed the BepinEx folder from the games root folder. Used the above downloaded files and replaced anything previous. Played for 10 minutes and had two crashes to desktop in that time.

**Comment by p1xel8ted** [comment]
> @p1xel8ted I removed the BepinEx folder from the games root folder. Used the above downloaded files and replaced anything previous. Played for 10 minutes and had two crashes to desktop in that time.

Random question, you using a controller or kb/mouse

**Comment by Dorsman** [comment]
Controller

**Comment by moistman7** [comment]
I also get crashes after about an hour of play. On controller too.
