### ISSUE TITLE
Prince of Persia - Map Alignment

### ISSUE THREAD

**Issue by RankFTW** [p1xel8ted/UltrawideFixes#15]
Hi.

Great work so far.

Prince of Persia.

The main map looks to be out of position, like my character icon is offset along with map icons etc.

**Comment by p1xel8ted** [comment]
There is indeed map issues. Gets worse the wider the aspect.

**Comment by RankFTW** [comment]
Thank you for the reply. Is this something you think you'll be able to fix?

**Comment by p1xel8ted** [comment]
> Thank you for the reply. Is this something you think you'll be able to fix?

Not at the moment. I need to fix some other tools that can assist first.

**Comment by yhuriez** [comment]
I have the same issue for a 3840*1080. I've have to reinstalled the game to remove the plugin, as it makes the game unplayable for now (the map is too importent for this type of game).
Can you please reconsider the priorization of this issue ?

**Comment by yhuriez** [comment]
Here is an example of the rendering :
![capture pop](https://github.com/p1xel8ted/UltrawideFixes/assets/15823366/99f366cb-2056-4673-9a19-951fee473f3c)

**Comment by mesii1019** [comment]
Firstly, thank you for creating this Ultra Wide Screen Fix! Having the same issue, definitely unable to play until this the map is fixed. Thank you again!

**Comment by p1xel8ted** [comment]
This is unlikely to be fixed; not by myself at least (at this stage). If someone wants to take a stab, by all means.

Doesn't mean I won't tinker with it, but don't hold out for a fix.
