### ISSUE TITLE
Hero: Road to Passion Ultrawide Fix < Any chance of doing this game?

### ISSUE THREAD

**Issue by 825i** [p1xel8ted/UltrawideFixes#19]
It's a unity game. Should be a ton easier than Sea of Stars to do.

It just adds black bars on the side and unfortunately you can't set any other resolution except 16:9 like 720p, 1080p, 4K etc.

I've tried Hex editors and even trying to appropriate your Sea of Stars fix.
Would be happy to tip you like I did for Sea of Stars.

**Comment by p1xel8ted** [comment]
WIP

**Comment by p1xel8ted** [comment]
@825i Give this a go. Not finished yet, still correcting UI elements, but the core of it is done.

https://github.com/p1xel8ted/UltrawideFixes/raw/main/HerosAdventureRoadToPassion/TestBuilds/HeroesAdventureRtP_Test.zip
