### ISSUE TITLE
Sea of Stars fishing visual glitch

### ISSUE THREAD

**Issue by WillScarlettOhara** [p1xel8ted/UltrawideFixes#2]
Hi,

I can't fish there.

![image](https://github.com/p1xel8ted/UltrawideFixes/assets/39462014/e0c1e307-1c94-4a23-a436-9a498aa6b8f2)

![image](https://github.com/p1xel8ted/UltrawideFixes/assets/39462014/fcfe0f7b-25c5-4633-8237-5a205db85dfa)

Gamepass version

**Comment by p1xel8ted** [comment]
Is this using version 0.1.6?

**Comment by WillScarlettOhara** [comment]
Yes and game version 1.0.46047

**Comment by p1xel8ted** [comment]
Try this one. Make sure you test transitioning between normal and fishing areas.

[SeaOfStars.zip](https://github.com/p1xel8ted/UltrawideFixes/files/12504814/SeaOfStars.zip)

**Comment by p1xel8ted** [comment]
Resolved in 0.1.7
