### ISSUE TITLE
[Agatha Christie - Murder on the Orient Express] Feature Suggestion

### ISSUE THREAD

**Issue by 1kFace8aby** [p1xel8ted/UltrawideFixes#21]
im sorry sir im new both from this game and github, idk if i post it here was right or not, forget my pardon. and the thing i wanna say is would u mind to add an increasing running speed or running speed value adjustment feature? the running speed in this game was too dang low

**Comment by p1xel8ted** [comment]
> im sorry sir im new both from this game and github, idk if i post it here was right or not, forget my pardon. and the thing i wanna say is would u mind to add an increasing running speed or running speed value adjustment feature? the running speed in this game was too dang low

What game

**Comment by 1kFace8aby** [comment]
> > 对不起，先生，我是这个游戏和 Github 的新手，如果我在这里发布它是对的还是不对的，请忘记我的原谅。我想说的是，您是否介意添加增加运行速度或运行速度值调整功能？这场比赛的奔跑速度太低了
> 
> 什么游戏

the Agatha Christie - Murder on the Orient Express, i saw this mod on the pcgamewiki

**Comment by p1xel8ted** [comment]
> > > 对不起，先生，我是这个游戏和 Github 的新手，如果我在这里发布它是对的还是不对的，请忘记我的原谅。我想说的是，您是否介意添加增加运行速度或运行速度值调整功能？这场比赛的奔跑速度太低了
> > 
> > 
> > 什么游戏
> 
> the Agatha Christie - Murder on the Orient Express, the 2023 one, i saw this mod on the pcgamewiki

https://github.com/p1xel8ted/UltrawideFixes/releases/tag/AgathaChristieMOE

**Comment by 1kFace8aby** [comment]
> > > > 对不起，先生，我是这个游戏和 Github 的新手，如果我在这里发布它是对的还是不对的，请忘记我的原谅。我想说的是，您是否介意添加增加运行速度或运行速度值调整功能？这场比赛的奔跑速度太低了
> > > 
> > > 
> > > 什么游戏
> > 
> > 
> > the Agatha Christie - Murder on the Orient Express, the 2023 one, i saw this mod on the pcgamewiki
> 
> https://github.com/p1xel8ted/UltrawideFixes/releases/tag/AgathaChristieMOE

thank you sir, ill check it out. much love

**Comment by 1kFace8aby** [comment]
oh i just found out this mod will lock my fps to the screens refresh rate, is it automaticly open the vsync or sth?

**Comment by 1kFace8aby** [comment]
i just found out it will change my fullscreen setting to full screen window and lock my fps to my refresh rate, and when i turn around or run in the game, the fps will drop a bit ,is there any option to change it back to fullscreen or unlock the fps? i have tried  the exclusive full screen at the f1 menu, but it seems doesn't work

**Comment by p1xel8ted** [comment]
> i just found out it will change my fullscreen setting to full screen window and lock my fps to my refresh rate, and when i turn around or run in the game, the fps will drop a bit which is make my game looks a little glithes. is there any option to change it back to fullscreen or unlock the fps? i have tried the exclusive full screen at the f1 menu, but it seems doesn't work
> 
> i saw the log saids :
> 
> [Warning: Unity Log] BoxColliders does not support negative scale or size. The effective box size has been forced positive and is likely to give unexpected collision geometry. If you absolutely need to use negative scaling you can use the convex MeshCollider. Scene hierarchy path "GO_ENV_C09_TrainRestau_Doors/FBX/FBX_PivotsWagonRestaurantDoors_Base/PivotDoor_Kitchen/GO_ENV_Door_OpenLeft_TrainRestauKitchen/Unity/Collisions"
> 
> is that the problem? idk how to judge these log things, but its the only thing looks unnormal there

Download latest (0.1.3) - the warnings in the log are from the game and not important

**Comment by 1kFace8aby** [comment]
thank you sir, ur so kind
