### ISSUE TITLE
Darkest Dungeon 2 Fix

### ISSUE THREAD

**Issue by nasuellia** [p1xel8ted/UltrawideFixes#22]
You're likely completely aware of this but while the "fix" works perfectly fine to make the correct resolution available, it does not really fixes the game's issues with ultrawide: the user interface is messed up both on the inn screen (mouse cursor does not match heroes when trying to apply inn items) and in several other places (black boxes, misalignements, etc).

**Comment by p1xel8ted** [comment]
Need screenshots, etc. Ideally a save game near the effected area.

**Comment by nasuellia** [comment]
Wait so you were NOT aware? Oh wow! Oo 
I'm glad to help then! I will produce all the necessary documentation as soon as possible (I might have the time today!)

**Comment by nasuellia** [comment]
Here's a youtube video for the issue that I wanted to report: https://youtu.be/1INrKR4jg7U?si=lG2oFySrtUJ7F7g8
Note that this does not appear to be some edge-case bug triggered by specific circumstances. The issue seems to be easily reproducible by simply getting to the very first inn.

Here's also a couple screenshots about an extremely minor imperfection, just in case you're a perfectionist XD
Right at the start of each region, the game splashes the region's name on the screen, with additional black bars at the top and the bottom, like this: 
![1V](https://github.com/p1xel8ted/UltrawideFixes/assets/17447903/ecd1c572-464b-4794-92b9-502e250b3062)

With the mod enabled, the black bar at the bottom is cut at a 16:9 size. Ignore the fact that in the screenshot, the region's name is not there, that is not the issue, I just I screen-capped a bit too late so it was already fading away (you can see the remainder of the "T"). Here's the screenshot with your mod:
![1M](https://github.com/p1xel8ted/UltrawideFixes/assets/17447903/340185ea-a7e0-4e2f-be8c-57f5a8a16d56)

Let me know if I can help in some other way.

**Comment by p1xel8ted** [comment]
I'll take a proper look on the weekend.

**Comment by nasuellia** [comment]
> I'll take a proper look on the weekend.

If you need other inputs I'm here! ;)

**Comment by p1xel8ted** [comment]
You can hover over the names, instead of the characters in the mean time.
