### ISSUE TITLE
[Prince of Persia: The Lost Crown] Ultrawide fix not applying? 

### ISSUE THREAD

**Issue by Shy** [p1xel8ted/UltrawideFixes#24]
Followed instructions and have the game booting. Once in game it won't provide resolutions past 2560x1440. Taking a look at the logs the mod seems to have installed correctly. 

I'm curious if the latest title update might have broken the mod. I am playing via a purchase through the epic store, but it loads through the ubisoft launcher. 

```log
Info   : Preloader] 0 patcher plugins loaded
[Info   : Preloader] 0 assemblies discovered
[Message:AssemblyPatcher] Executing 0 patch(es)
[Message:   BepInEx] Chainloader initialized
[Info   :   BepInEx] 1 plugin to load
[Info   :   BepInEx] Loading [Prince of Persia: The Lost Crown Ultra-Wide 0.1.4]
[Info   :Prince of Persia: The Lost Crown Ultra-Wide] Plugin Prince of Persia: The Lost Crown Ultra-Wide is loaded!
```

![image](https://github.com/p1xel8ted/UltrawideFixes/assets/1316340/babd7618-6458-456d-941d-8444d16d9220)

**Comment by p1xel8ted** [comment]
It is indeed broken in the latest game update - but not just the mod, BepInEx itself.
