### ISSUE TITLE
[Core Keeper] Ultrawide mod crashes game instantly (R2ModMan)

### ISSUE THREAD

**Issue by BlueASIS** [p1xel8ted/UltrawideFixes#26]
most recent version(0.7.5.2-3339) as of 29/06/2024 

mod version in R2ModMan is stuck at v0.0.2

can confirm manual install works fine!

**Comment by mccorkle** [comment]
Confirming that Core Keeper appears to get stuck on launch screen.  Happens even when I launch with no other mods enabled. 

Game Version: 0.9.9-9008 (Updated 2024-08-26) 
BepInEx: 6.0.0-be.688 

Windows 11 Pro 
3440x1440
RTX4070 Ti Super

Errors which I see in the console:
```
[Error  : Unity Log] MissingMethodException: Method not found: void .Manager.InitializeGlobalManager()
Stack trace:
(wrapper dynamic-method) LoadingScene.DMD<LoadingScene::Awake>(LoadingScene)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
Sentry.Unity.Integrations.UnityLogHandlerIntegration:LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)

[Error  : Unity Log] MissingFieldException: Field not found: bool PugRP.PugCamera.outputSmoothing Due to: Could not find field in class
Stack trace:
CoreKeeper.Plugin.SceneManagerOnSceneLoaded (UnityEngine.SceneManagement.Scene a, UnityEngine.SceneManagement.LoadSceneMode l) (at <f4b4b0fc90914f6bbff970cd7c910c9d>:0)
UnityEngine.SceneManagement.SceneManager.Internal_SceneLoaded (UnityEngine.SceneManagement.Scene scene, UnityEngine.SceneManagement.LoadSceneMode mode) (at <1125f841996a4ae78a651c0566f655f8>:0)
UnityEngine.DebugLogHandler:LogException(Exception, Object)
Sentry.Unity.Integrations.UnityLogHandlerIntegration:LogException(Exception, Object)
UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
```

Full LogOutut.log attached.
[LogOutput.log](https://github.com/user-attachments/files/16748967/LogOutput.log)

**Comment by p1xel8ted** [comment]
Are you using the one from modio, or the one here in github

**Comment by p1xel8ted** [comment]
> Confirming that Core Keeper appears to get stuck on launch screen. Happens even when I launch with no other mods enabled.
> 
> Game Version: 0.9.9-9008 (Updated 2024-08-26) BepInEx: 6.0.0-be.688
> 
> Windows 11 Pro 3440x1440 RTX4070 Ti Super
> 
> Errors which I see in the console:
> 
> ```
> [Error  : Unity Log] MissingMethodException: Method not found: void .Manager.InitializeGlobalManager()
> Stack trace:
> (wrapper dynamic-method) LoadingScene.DMD<LoadingScene::Awake>(LoadingScene)
> UnityEngine.DebugLogHandler:LogException(Exception, Object)
> Sentry.Unity.Integrations.UnityLogHandlerIntegration:LogException(Exception, Object)
> UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
> 
> [Error  : Unity Log] MissingFieldException: Field not found: bool PugRP.PugCamera.outputSmoothing Due to: Could not find field in class
> Stack trace:
> CoreKeeper.Plugin.SceneManagerOnSceneLoaded (UnityEngine.SceneManagement.Scene a, UnityEngine.SceneManagement.LoadSceneMode l) (at <f4b4b0fc90914f6bbff970cd7c910c9d>:0)
> UnityEngine.SceneManagement.SceneManager.Internal_SceneLoaded (UnityEngine.SceneManagement.Scene scene, UnityEngine.SceneManagement.LoadSceneMode mode) (at <1125f841996a4ae78a651c0566f655f8>:0)
> UnityEngine.DebugLogHandler:LogException(Exception, Object)
> Sentry.Unity.Integrations.UnityLogHandlerIntegration:LogException(Exception, Object)
> UnityEngine.Debug:CallOverridenDebugHandler(Exception, Object)
> ```
> 
> Full LogOutut.log attached. [LogOutput.log](https://github.com/user-attachments/files/16748967/LogOutput.log)

https://github.com/p1xel8ted/UltrawideFixes/releases/download/CoreKeeper/01.CoreKeeper_v0.1.1_Windows.zip

**Comment by mccorkle** [comment]
Thank you for the quick fix.  Tested with the new 1.0.0.1 release of the game today with the UltrawideFixes v0.1.1, and that fixed the crash.
