### ISSUE TITLE
Klonoa Fov

### ISSUE THREAD

**Issue by emanuelect** [p1xel8ted/UltrawideFixes#27]
Hi, ho notato che il fov è leggermente troppo distante, anche impostato a 0. Ho avuto un pò di difficoltà a superare gli ostacoli di questo livello : https://www.youtube.com/watch?v=pvkvLQb_xIE&t=3745s

**Comment by p1xel8ted** [comment]
[KlonoaSeries.zip](https://github.com/user-attachments/files/16247111/KlonoaSeries.zip)


> Hi, ho notato che il fov è leggermente troppo distante, anche impostato a 0. Ho avuto un pò di difficoltà a superare gli ostacoli di questo livello : https://www.youtube.com/watch?v=pvkvLQb_xIE&t=3745s

**Comment by emanuelect** [comment]
grazie, funziona alla grande.
