### ISSUE TITLE
Floor tiles still popping in and out as player moves with MaxWidth at max

### ISSUE THREAD

**Issue by mccorkle** [p1xel8ted/UltrawideFixes#29]
The floor tiles popping in and out when moving horizontal.  I tried adjusting `Max Width` and `Dont Destroy Tiles`, but still appears to be popping the tile visuals out and back in.  Is this something that is player fixable?  

Game version: 1.0.0.1 (2024-08-27) 
UltraWideFixes release:  01.CoreKeeper_v0.1.1_Windows.zip
Windows 11 Pro
Display: 3440x1440 

![Screenshot 2024-08-27 074506](https://github.com/user-attachments/assets/12cdbe6b-c0dd-4bdd-a997-45469a19c84d)

**Comment by p1xel8ted** [comment]
This is mentioned on the release page. But no, nothing you can do at your end. The tile gen/degen is quite complex and I haven't found a way to correct it for the wider aspects yet. The don't destroy tiles option no longer does anything. Will re-visit it later.

https://github.com/p1xel8ted/UltrawideFixes/releases/tag/CoreKeeper
