### ISSUE TITLE
Sea of Stars Shadows/Odd Text/UI Position

### ISSUE THREAD

**Issue by premiumghoul** [p1xel8ted/UltrawideFixes#3]
Hey, I saw a video of your mod and thought I'd try it out. The game does look stunning in 21:9 but unfortunately it seems to make some effects not display correctly.
![Screenshot (43)](https://github.com/p1xel8ted/UltrawideFixes/assets/127659842/4075a579-14d3-4b35-b2a1-f9442fabca1b)
![Screenshot (44)](https://github.com/p1xel8ted/UltrawideFixes/assets/127659842/2efe593a-c403-4c35-ad80-92d076436c82)

With the mod active all the subtle shadows in the environment become spotty, almost like a halftone pattern. The fire effect on the flaming torches also looks like it's rendering at native resolution compared to the rest of the scene.

**Comment by p1xel8ted** [comment]
Not game breaking, so I'll take a look when I can.

**Comment by LiamMoseley** [comment]
Just to point out, the shadows are also rendering at native resolution, losing their pixelated look.

**Comment by p1xel8ted** [comment]
I accidentally stumbled across what causes this, should be able to fix it.

**Comment by p1xel8ted** [comment]
@premiumghoul @LiamMoseley, Can you please test both of these versions and report back on what the UI positioning is like? I've fixed the reported issues, but it messes with my UI fix. I also need to know what ultrawide resolution you used.

[SeaOfStars_v0.1.8_TestOne.zip](https://github.com/p1xel8ted/UltrawideFixes/files/12558538/SeaOfStars_v0.1.8_TestOne.zip)
[SeaOfStars_v0.1.8_TestTwo.zip](https://github.com/p1xel8ted/UltrawideFixes/files/12558532/SeaOfStars_v0.1.8_TestTwo.zip)

**Comment by premiumghoul** [comment]
I'm using 3440x1440 resolution. Both of those fixes appear identical to me with the HUD centered.

**Comment by p1xel8ted** [comment]
Still need reports from the other resolutions.

**Comment by Garbosh52** [comment]
![Screenshot 2023-09-14 114910](https://github.com/p1xel8ted/UltrawideFixes/assets/145042823/42633479-279a-4d8a-9644-a438ee265c2d)
![Screenshot 2023-09-14 115036](https://github.com/p1xel8ted/UltrawideFixes/assets/145042823/7f155146-a135-4031-a5c3-b9df94083212)
Definitely a little off center @ 2560x1080.  Haven't gotten farther in than just a battle to test.  Will check other back once I can see more of it.

**Comment by p1xel8ted** [comment]
> ![Screenshot 2023-09-14 114910](https://github.com/p1xel8ted/UltrawideFixes/assets/145042823/42633479-279a-4d8a-9644-a438ee265c2d)
> ![Screenshot 2023-09-14 115036](https://github.com/p1xel8ted/UltrawideFixes/assets/145042823/7f155146-a135-4031-a5c3-b9df94083212)
> Definitely a little off center @ 2560x1080.  Haven't gotten farther in than just a battle to test.  Will check other back once I can see more of it. 
> 
> Edit: After reading notes further moved UI using method mentioned working great.  I don't notice any difference in the lighting from the original version.  Biggest difference I have noticed is in the Sea of Stars into page.  And the fact it works @ 2560x1080.  
> 
> About to try fishing and see how the fix works there.
> 
> Edit 2: Noticed a character deformity in the "i" in Sea of Nightmares.
> 
> ![Screenshot 2023-09-14 162228](https://github.com/p1xel8ted/UltrawideFixes/assets/145042823/0e51f517-14a5-476a-8b35-bacfa06ce99d)
> 

Without using a custom UI position, which version of 0.1.8 (TestOne or TestTwo) did you try? Or is the positioning the same?

**Comment by Garbosh52** [comment]
TestOne is better than test two for me. TestTwo positioned it further left than TestOne.

Just got the boat and all is still well except for ??? fishing spot on small island in the south is broken...ish.  


![Screenshot 2023-09-14 181224](https://github.com/p1xel8ted/UltrawideFixes/assets/145042823/f56923f6-3a47-4417-baf1-49480549469a)

**Comment by p1xel8ted** [comment]
#5

**Comment by p1xel8ted** [comment]
> TestOne is better than test two for me. TestTwo positioned it further left than TestOne.
> 
> Just got the boat and all is still well except for ??? fishing spot on small island in the south is broken...ish.  
> 
> 
> ![Screenshot 2023-09-14 181224](https://github.com/p1xel8ted/UltrawideFixes/assets/145042823/f56923f6-3a47-4417-baf1-49480549469a)
> 

https://github.com/p1xel8ted/UltrawideFixes/issues/6

Can you please attach a save game near the affected area to the issue above?

**Comment by TerraDK** [comment]
> @TerraDK
> 
> > Works fine with manual install. Running on Full screen at 3840x1600.
> > Texts (even version # at the bottom) is looking very strange.
> > ![SeaOfStars_TD7lcSp5hI](https://user-images.githubusercontent.com/46207023/268198385-ea6504c7-7fba-4a28-b475-9a64e60cb888.png)
> > ![SeaOfStars_1KLyV2Cuoe](https://user-images.githubusercontent.com/46207023/268198391-2e250986-f463-43ef-a4fd-8539538bb42d.png)
> 
> 0.1.8 TestOne or TestTwo

Wasn't aware of open issue already, apologies.

I've tried it all 3 ways: with 0.1.8Windows, TestOne, and TestTwo. They all have same results for text being bloated/weird.

In addition, when moving around, the textures/graphics seem a bit distorted as well. Its fine when standing still. Seems related, as it does not happen with default base game.

Thanks for your hard work.

**Comment by p1xel8ted** [comment]
> > @TerraDK
> > 
> > > Works fine with manual install. Running on Full screen at 3840x1600.
> > > Texts (even version # at the bottom) is looking very strange.
> > > ![SeaOfStars_TD7lcSp5hI](https://user-images.githubusercontent.com/46207023/268198385-ea6504c7-7fba-4a28-b475-9a64e60cb888.png)
> > > ![SeaOfStars_1KLyV2Cuoe](https://user-images.githubusercontent.com/46207023/268198391-2e250986-f463-43ef-a4fd-8539538bb42d.png)
> > 
> > 0.1.8 TestOne or TestTwo
> 
> Wasn't aware of open issue already, apologies.
> 
> I've tried it all 3 ways: with 0.1.8Windows, TestOne, and TestTwo. They all have same results for text being bloated/weird.
> 
> In addition, when moving around, the textures/graphics seem a bit distorted as well. Its fine when standing still. Seems related, as it does not happen with default base game.
> 
> Thanks for your hard work.

All good. How was the default UI positioning with each version?

**Comment by TerraDK** [comment]
> > > @TerraDK
> > > > Works fine with manual install. Running on Full screen at 3840x1600.
> > > > Texts (even version # at the bottom) is looking very strange.
> > > > ![SeaOfStars_TD7lcSp5hI](https://user-images.githubusercontent.com/46207023/268198385-ea6504c7-7fba-4a28-b475-9a64e60cb888.png)
> > > > ![SeaOfStars_1KLyV2Cuoe](https://user-images.githubusercontent.com/46207023/268198391-2e250986-f463-43ef-a4fd-8539538bb42d.png)
> > > 
> > > 
> > > 0.1.8 TestOne or TestTwo
> > 
> > 
> > Wasn't aware of open issue already, apologies.
> > I've tried it all 3 ways: with 0.1.8Windows, TestOne, and TestTwo. They all have same results for text being bloated/weird.
> > In addition, when moving around, the textures/graphics seem a bit distorted as well. Its fine when standing still. Seems related, as it does not happen with default base game.
> > Thanks for your hard work.
> 
> All good. How was the default UI positioning with each version?

UI position was good with both. I didn't get in battle but talked to NPCs and opened menu, it was centered properly in both. I can get in battle if you would like me to.

**Comment by p1xel8ted** [comment]
> > > > @TerraDK
> > > > > Works fine with manual install. Running on Full screen at 3840x1600.
> > > > > Texts (even version # at the bottom) is looking very strange.
> > > > > ![SeaOfStars_TD7lcSp5hI](https://user-images.githubusercontent.com/46207023/268198385-ea6504c7-7fba-4a28-b475-9a64e60cb888.png)
> > > > > ![SeaOfStars_1KLyV2Cuoe](https://user-images.githubusercontent.com/46207023/268198391-2e250986-f463-43ef-a4fd-8539538bb42d.png)
> > > > 
> > > > 
> > > > 0.1.8 TestOne or TestTwo
> > > 
> > > 
> > > Wasn't aware of open issue already, apologies.
> > > I've tried it all 3 ways: with 0.1.8Windows, TestOne, and TestTwo. They all have same results for text being bloated/weird.
> > > In addition, when moving around, the textures/graphics seem a bit distorted as well. Its fine when standing still. Seems related, as it does not happen with default base game.
> > > Thanks for your hard work.
> > 
> > All good. How was the default UI positioning with each version?
> 
> UI position was good with both. I didn't get in battle but talked to NPCs and opened menu, it was centered properly in both. I can get in battle if you would like me to.

That would be good please

**Comment by TerraDK** [comment]
TestOne
![SeaOfStars_Etp2QN1Wvf](https://github.com/p1xel8ted/UltrawideFixes/assets/46207023/6f72172a-daba-4f79-bd54-5828893f7f33)

TestTwo
![SeaOfStars_IN5eZtp3rw](https://github.com/p1xel8ted/UltrawideFixes/assets/46207023/ae978ad3-08d9-491a-bfc4-d9c76621e5c3)

**Comment by Garbosh52** [comment]
> > TestOne is better than test two for me. TestTwo positioned it further left than TestOne.
> > Just got the boat and all is still well except for ??? fishing spot on small island in the south is broken...ish.
> > ![Screenshot 2023-09-14 181224](https://user-images.githubusercontent.com/145042823/268123406-f56923f6-3a47-4417-baf1-49480549469a.png)
> 
> #6
> 
> Can you please attach a save game near the affected area to the issue above?

Once I can leave Antsudlo I shall do so for you.

**Comment by p1xel8ted** [comment]
https://github.com/p1xel8ted/UltrawideFixes/issues/8#issuecomment-1722286232

**Comment by falcodee** [comment]
Hello, how can i fix this problem? I already tried all versions, and only the newest "work" like that. Previous versions crash everytime when i start them. It open only the MelonLoader console window and then crash, without any error window or whatever. 
![Snímek obrazovky 2023-10-12 180626](https://github.com/p1xel8ted/UltrawideFixes/assets/147746215/a38cfe58-d595-459c-8638-22b2cd61f2c9)

Ok update: when i switch back to the newest version. It crash too like before.. omg

**Comment by p1xel8ted** [comment]
> Hello, how can i fix this problem? I already tried all versions, and only the newest "work" like that. Previous versions crash everytime when i start them. It open only the MelonLoader console window and then crash, without any error window or whatever. 
> ![Snímek obrazovky 2023-10-12 180626](https://github.com/p1xel8ted/UltrawideFixes/assets/147746215/a38cfe58-d595-459c-8638-22b2cd61f2c9)
> 
> ![Snímek obrazovky 2023-10-12 200322](https://github.com/p1xel8ted/UltrawideFixes/assets/147746215/2be13141-3955-4d71-8290-a676b543409f)
> 
> 

When you switch versions you need to delete the configuration file
