### ISSUE TITLE
[Core Keeper] v1.0.0.2: Ultrawide fixes still show pop-in and tile destruction

### ISSUE THREAD

**Issue by pocketlim** [p1xel8ted/UltrawideFixes#30]
Yes, I know there is an issue for it that is closed here: https://github.com/p1xel8ted/UltrawideFixes/issues/29 but I believe we should leave this up as an actual issue until resolved. 

Core Keeper v1.0.0.2 
using https://github.com/p1xel8ted/UltrawideFixes/releases/download/CoreKeeper/01.CoreKeeper_v0.1.1_Windows.zip 

Thanks for the mod! Just gonna wait until it's resolved.

**Comment by DAOWAce** [comment]
Oh, so the option is non-functional, welp.

Really no reason to use this fix now.  The culling is extremely distracting.

Can't believe it's been 3 years since the dev stated no ultrawide support was planned, and now the game is in 1.0 on multiple platforms and still no word about further support.
