### ISSUE TITLE
[Shadow of the Ninja - Reborn] Is there a possibility of moving the HUD inward towards the time for 4:3 and 5:4 Displays?

### ISSUE THREAD

**Issue by uberdisko** [p1xel8ted/UltrawideFixes#32]
Is there a possibility of moving the HUD inward towards the time for 4:3 and 5:4 Displays?

**Comment by p1xel8ted** [comment]
What fix

**Comment by uberdisko** [comment]
![IMG_20240908_1417272](https://github.com/user-attachments/assets/e620ef96-d09b-4656-9f57-3c5fc6627499)

![Screenshot (1)](https://github.com/user-attachments/assets/54a475a7-b804-4415-8b05-bc381e628201)

ok so first off the Ultrawide Fix you have made is working beautifully!!! its even working in reverse for people like me trying to use a CRT or 5:4 LCD Panels! but the only issue with compressing the Playfield that much is that you ended up cutting off the Health Bars, so if there is a way to fit them in the Playfield that would be awesome

Thank you again for putting out this amazing fix!

**Comment by p1xel8ted** [comment]
@uberdisko please try the new release

https://github.com/p1xel8ted/UltrawideFixes/releases/tag/ShadowOfTheNinja

**Comment by uberdisko** [comment]
ok that worked amazingly to fix the HUD issue... but i have now found a new issue inhibiting 4:3/5:4 Aspect Ratios - you cannot leave Certain Levels if the Door is out of the Playfield , is there anyway you could add a Zoom Scale? i wouldnt mind Playing Slightly Bordered if i could exit Doors lol, but for now you can either Play in 720x480 or hit F5 and True 21:9 and then you can proceed to the next section of the game in areas like this

https://github.com/user-attachments/assets/8f4226cb-5134-4f85-8c9f-461738b801ed

**Comment by p1xel8ted** [comment]
That is a little more complex. I can zoom out no problem, but they've tied the UI to the cameras, so the UI position changes on zoom.
