### ISSUE TITLE
[The Rogue Prince of Persia] UI Scaling

### ISSUE THREAD

**Issue by AT-4** [p1xel8ted/UltrawideFixes#33]
Hi, ultrawide fix is working great, and I know there's a UI scaling section to this mod in the F5 menu, but was wondering if there's any way of adjusting the positioning of the UI so we could move it inwards?

**Comment by p1xel8ted** [comment]
You mean, you don't want the UI spanned?

**Comment by p1xel8ted** [comment]
> Hi, ultrawide fix is working great, and I know there's a UI scaling section to this mod in the F5 menu, but was wondering if there's any way of adjusting the positioning of the UI so we could move it inwards?

Added in 0.1.2
