### ISSUE TITLE
[Witchspring R] UI issue 

### ISSUE THREAD

**Issue by Nyvill** [p1xel8ted/UltrawideFixes#34]
![image](https://github.com/user-attachments/assets/40f132dc-1d64-4bdc-a6ae-17c7b7df3edf)
hey, just got the game and downloaded ur fix but the UI in the witchhouse seems to not work

**Comment by p1xel8ted** [comment]
I'll have to redownload the game and check - thanks for reporting it.

**Comment by p1xel8ted** [comment]
![image](https://github.com/user-attachments/assets/49fbe3a1-b1d1-4f24-a939-92682223c196)

No issues here. Will need a log file - found in the BepInEx folder
