### ISSUE TITLE
HUD Issues with Witchspring R

### ISSUE THREAD

**Issue by Dervah** [p1xel8ted/UltrawideFixes#35]
![HUD issues](https://github.com/user-attachments/assets/1f5d696e-2e17-46e2-94b2-a8e50fbd998d)

I'm currently having issues where the tutorials completely blocked out the display and makes it very difficult to progress.

Whenever an NPC has dialogue, their speech bubble extends past the screen and the text is impossible to read.

Adding WINEDLLOVERRIDES="winhttp=n,b" %command% to the steam launch options gave me an error so I didn't include it. However it launches in ultrawide just fine without

I'll gladly get you a coffee if you're able to help me with these issues!

**Comment by Dervah** [comment]
![HUD issues 2](https://github.com/user-attachments/assets/c7a19e70-26c7-4ff9-b914-54f4ac90cda9)

Example of the unreadable dialogue

**Comment by p1xel8ted** [comment]
@Dervah 

Can you please share your save game.

**Comment by Dervah** [comment]
GitHub keeps saying "We don't support that file type". How do I share it?

**Comment by Dervah** [comment]
[1958220.zip](https://github.com/user-attachments/files/17265302/1958220.zip)

**Comment by p1xel8ted** [comment]
> [1958220.zip](https://github.com/user-attachments/files/17265302/1958220.zip)

Fixed in 0.1.3 - https://github.com/p1xel8ted/UltrawideFixes/releases/tag/WitchSpringR

**Comment by Dervah** [comment]
It works perfectly, you're the best!

**Comment by Dervah** [comment]
Thank you!
