### ISSUE TITLE
[Crow Country] Update broke Ultrawide fix

### ISSUE THREAD

**Issue by adhdandy** [p1xel8ted/UltrawideFixes#36]
After the recent [update](https://steamdb.info/app/1996010/history/?changeid=25748878) Ultrawide Fix doesn't load anymore.

**Comment by p1xel8ted** [comment]
@adhdandy They've converted the game to IL2CPP (requirement for releasing on consoles). Will take a bit to update.

**Comment by p1xel8ted** [comment]
Fixed in 0.1.2

https://github.com/p1xel8ted/UltrawideFixes/releases/tag/CrowCountry
