### ISSUE TITLE
Sea of stars: cropped cutscenes

### ISSUE THREAD

**Issue by maicol07** [p1xel8ted/UltrawideFixes#37]
With the mod, cutscenes are cropped and are not fully visible

**Comment by p1xel8ted** [comment]
Please provide a save game near the cutscene and instructions to trigger it

**Comment by maicol07** [comment]
Unfortunately, I have overwritten the save slots before the cutscene. I'll provide one when I get a new one.

However, I think this is also triggered in the initial cutscene when you reach Mooncradle Village in the first hour of the game in the flashback with the kid characters

**Comment by maicol07** [comment]
@p1xel8ted Just got a new one: here is my save file (from the Game pass version, I think it should be convertible to the Steam one):
[9A05CC90435C408EAA17FFC399E60FF0.zip](https://github.com/user-attachments/files/17550229/9A05CC90435C408EAA17FFC399E60FF0.zip)
To trigger the cutscene follow the path to the left until a whirlpool. Follow it and you'll reach the boss. After a few battle turns the cutscene will trigger

**Comment by p1xel8ted** [comment]
Fixed in 0.3.1+
