### ISSUE TITLE
Update "Sea of Stars Dawn of Equinox" released the 12 Nov Broken your Fix.

### ISSUE THREAD

**Issue by The-Gaymer** [p1xel8ted/UltrawideFixes#39]
The Update "Sea of Stars Dawn of Equinox" released the 12 Nov Broken your Fix.

- Windows called with F5 doesn't work (freeze)

- Fishing is broken (right side of the screen)
https://youtu.be/KN2-JLghlfM?si=mofd7gZS3JFxx9ee&t=4515

- Some time, when going "open world", having black screen (have to press windows key and go back in game to show the game again)
https://youtu.be/KN2-JLghlfM?si=GcS0btGeRnOBCtnG&t=4385
(can't be see here because OBS still capture video well, but my screen was black here, weird...Happened many time when going "open-world")

- Some Time Transition are buggued (Gigantic HP bar Spawn)
https://youtu.be/KN2-JLghlfM?si=shXhLxmIE_Xhr2O6&t=80
https://youtu.be/KN2-JLghlfM?si=gFtp-CJKeVpmFPS8&t=210
https://youtu.be/KN2-JLghlfM?si=jfP2zAm15hkoh8JR&t=424

**Comment by p1xel8ted** [comment]
Add your save game with instructions on getting to each bug.

**Comment by The-Gaymer** [comment]
?.. 🤔
Just read each link vidéo ?..

**Comment by p1xel8ted** [comment]
@The-Gaymer 

[SeaOfStarsUltraWide.zip](https://github.com/user-attachments/files/17830236/SeaOfStarsUltraWide.zip)

I'm going to bed now. This is approaching the fix from a different angle, test out and let me know.

**Comment by The-Gaymer** [comment]
what "override" are you talking about ?..

`[Preloader]

## Specifies which MonoMod backend to use for Harmony patches. Auto uses the best available backend.
## This setting should only be used for development purposes (e.g. debugging in dnSpy). Other code might override this setting.
# Setting type: MonoModBackend
# Default value: auto
# Acceptable values: auto, dynamicmethod, methodbuilder, cecil
HarmonyBackend = auto
`

`## If enabled, BepInEx will load patched assemblies from BepInEx/DumpedAssemblies instead of memory.
## This can be used to be able to load patched assemblies into debuggers like dnSpy.
## If set to true, will override DumpAssemblies.
# Setting type: Boolean
# Default value: false
LoadDumpedAssemblies = false`

?

**Comment by p1xel8ted** [comment]
Did you test it or just ignore my instructions?

**Comment by p1xel8ted** [comment]
You've asked if I've fixed something without testing the new fix. It goes into BepInEx/plugins. 

Open the config manager config, not the BepInEx config.

**Comment by The-Gaymer** [comment]
> It goes into BepInEx/plugins.
> 
> Open the config manager config, not the BepInEx config.

Thanks for answer, i'm in work, so i will test it this night or tomorow (French time)

**Comment by The-Gaymer** [comment]
1/ by setting the 
`## Disables the overriding of the EventSystem from the game, if you experience issues with UI Input.
# Setting type: Boolean
# Default value: false
Disable EventSystem Override = false`
From true to false, the "F5-window" now work fine :)

2/ by paste your file in the "BepInEx/plugins" folder, everything seem's to work fine (can't test fishing yet).

3/ Unfortunatly, since now, the Font Text (and everything actually) is very weird and almost unreadable, it's like i have a filter that make the game more pixelish, any idea ? :O
![image](https://github.com/user-attachments/assets/020df28d-f32d-4d8c-abdf-3788398b892b)

**Comment by The-Gaymer** [comment]
Btw, any way to make the party run faster ? like x1.5 Please ? :)

**Comment by p1xel8ted** [comment]
What screen res are you using?

**Comment by The-Gaymer** [comment]
3440x1440

**Comment by p1xel8ted** [comment]
![image](https://github.com/user-attachments/assets/2c7439bb-efe6-44fb-9372-ce928f1ead92)

Curious, I'm also 3440x1440

**Comment by p1xel8ted** [comment]
[SeaOfStars-WIP2.zip](https://github.com/user-attachments/files/17879125/SeaOfStars-WIP2.zip)

- Fishing fixed. Will be pillarboxed while fishing, this is intentional.
- All transition screens should be fixed now
- Added options to adjust the UI pixel width - should not need to use it, but if you get weird text, give it a shot

**Comment by p1xel8ted** [comment]
https://ko-fi.com/p1xel8ted

**Comment by The-Gaymer** [comment]
Do this Fix have been inplemented in your Current Fix ?
"https://github.com/p1xel8ted/UltrawideFixes/releases/download/SeaOfStars/CURRENT.-.01.SeaOfStars_v0.3.0_BepInEx.exe"

**Comment by p1xel8ted** [comment]
Not yet

**Comment by The-Gaymer** [comment]
Ok.
Unfortunatly, i can't find the setting to fix the Pixel Bug :'(
https://youtu.be/2GJhYZdD-ac

**Comment by The-Gaymer** [comment]
i had to set back "Disable EventSystem Override = false" => true to fix the pixel, but i can't use F5-Window no more, but it doesn't matter because it save the run speed x1.5, and i no more use this window :D

**Comment by p1xel8ted** [comment]
You gotta read the settings your playing with.

You're trying to adjust the pixel width, but you havent enabled the option

**Comment by The-Gaymer** [comment]
> You gotta read the settings you're playing with.
> 
> You're trying to adjust the pixel width, but you haven't enabled the option - you also have to close the menu after you do to see the effects.
> 
> Fixed the category, should be clearer now
> 
> [SeaOfStars-WIP3.zip](https://github.com/user-attachments/files/17879357/SeaOfStars-WIP3.zip)

Tested, but still can't find the pixel-perfect pos :'(
https://youtu.be/TsPPgM6BKUM?si=kkEBgwtBKQZry4P0

**Comment by The-Gaymer** [comment]
Btw, it seem i can't use this mod with yours 😢
https://www.nexusmods.com/seaofstars/mods/3

**Comment by p1xel8ted** [comment]
Works fine (image might be brighter than normal due to HDR)

![image](https://github.com/user-attachments/assets/650f31df-b568-4065-9567-1d9f773add1c)
![image](https://github.com/user-attachments/assets/c0eb3733-0291-43e0-b3d5-ed6b620dd799)

**Comment by The-Gaymer** [comment]
> Works fine (image might be brighter than normal due to HDR)
> 
> ![image](https://private-user-images.githubusercontent.com/10510767/389192799-650f31df-b568-4065-9567-1d9f773add1c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNjMzNzgsIm5iZiI6MTczMjM2MzA3OCwicGF0aCI6Ii8xMDUxMDc2Ny8zODkxOTI3OTktNjUwZjMxZGYtYjU2OC00MDY1LTk1NjctMWQ5Zjc3M2FkZDFjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDExNTc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWVhZTgyYTA3ZDY0ZWFiYzYwYTJjOThjNWJjNTdiMjYwM2JmYTUwOWQ1NjQzNTRjZGVjMmZlYzAwMTIwMWE4MDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.erR5M_Lb7W_-CccuECXCIPpJnf_2M0ezikAYV3Jm_NM) ![image](https://private-user-images.githubusercontent.com/10510767/389192849-c0eb3733-0291-43e0-b3d5-ed6b620dd799.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzIzNjMzNzgsIm5iZiI6MTczMjM2MzA3OCwicGF0aCI6Ii8xMDUxMDc2Ny8zODkxOTI4NDktYzBlYjM3MzMtMDI5MS00M2UwLWIzZDUtZWQ2YjYyMGRkNzk5LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDExMjMlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMTIzVDExNTc1OFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWRlMjdmMjlkYzYxZGM0N2JjNjhkNzdjNTE0OTk0Y2MxZjBkY2M5YzVlOTc1Y2ZiYTk1YWU5ZDcxNWNmNzkwNTQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0._6oI8oy-XZJqWPrKyWuZ7SCTyaL1abDe75VZ_ab48lk)

Ok, i understand why it doesn't work properly.
once in two, i have the pixel bug comback when lunching the game.
I have to restart the game, and so, the Mod bug too ^^'
