### ISSUE TITLE
Black screen issue on transition screens

### ISSUE THREAD

**Issue by AynelTwinmoon** [p1xel8ted/UltrawideFixes#4]
Hello UltrawideFixes devs,

I just started playing Sea of Stars and immediately downloaded the mod. However, whenever I have a transition screen (see the attached screenshot below) I have a pure black screen that "freezes" the game. I still hear the little dialogue box and the loading screen, but it seems it never reaches past the loading.
With the example screenshot below (had to take it from a gameplay video) the text doesn't appear on the screen, basically leaving me with a black screen. I hear the letters popping sound which makes me believe it doesn't block or stop the game from sort of running in the background, but it remains all dark and nothing else happens. The music and ambience sounds still play in the background, but that's it. It also seems it never really leave this transition screen or passes the loading screen as I have no other dialogue popping sound or anything else whatsoever, just the sounds that were present during the transition screen.

![sea_of_stars_issue](https://github.com/p1xel8ted/UltrawideFixes/assets/41022377/c62bc79c-de95-4e8b-9ae9-74298874e51d)

It does not seem to corrupt the save in any way since I can load the game, but it makes it unplayable with the ultrawide mod.

Some info
- game version: 1.0.46074, on Steam
- mod version: 0.1.8
- install method: manual (unzipped file in game root directory)
- windows 10

**Comment by p1xel8ted** [comment]
A save game near the affected area would be immensely helpful.

**Comment by AynelTwinmoon** [comment]
Sure, where can I access the logs?
