### ISSUE TITLE
Metal Slug Tactics - Linux

### ISSUE THREAD

**Issue by powerofthe69** [p1xel8ted/UltrawideFixes#40]
Wasn't sure what the right way to do this was, but I just wanted to leave a note for anyone else on Linux, specifically Fedora Silverblue like me.

Unzipping the file by using the GUI in Nautilus gives the error `unsupported zip compression method (9 deflation-64-bit)`. If you unzip the file in the CLI by running `unzip MetalSlugTactics_v0.1.0_BepInEx.zip`, it works OOTB, however. Then you just move the extracted files and folder into the game directory, add the DLL Override option in Steam, and it works without issues.

Hope this helps and thanks to @p1xel8ted  for your continued dedication to making ultrawide better!!

**Comment by p1xel8ted** [comment]
Thanks for this - would you mind testing this zip file for me?

[Test.zip](https://github.com/user-attachments/files/17895459/Test.zip)

**Comment by powerofthe69** [comment]
That one worked in the GUI. Thanks!! That makes it easier for anyone that doesn't like to tinker with the CLI
