### ISSUE TITLE
Nine Sols fade overlay resets after opening the menu

### ISSUE THREAD

**Issue by PGGB** [p1xel8ted/UltrawideFixes#43]
Hey, first of all thanks a lot for the work you do!

I've been using the Nine Sols plugin and it has worked perfectly so far. But now I've hit the prison section where the screen is darkened and after I open the map the darkened corners overlay resets to the non-ultrawide dimensions until I restart the game:
![20241209213445_1](https://github.com/user-attachments/assets/15620a37-7e1a-48e4-9b87-53fd2b799f5b)
![20241209213459_1](https://github.com/user-attachments/assets/5497de65-5df2-4e1c-9225-85199a502733)

If you have an idea how to fix it I would appreciate it a lot! I'm not very knowledgeable in modding Unity games, so it would probably take me a while to work out how to fix it.

**Comment by p1xel8ted** [comment]
Hey @PGGB 

Are you able to share the save game for that specific location?

**Comment by PGGB** [comment]
Sure thing, this should be it:
[saveslot0.zip](https://github.com/user-attachments/files/18085160/saveslot0.zip)

**Comment by p1xel8ted** [comment]
> Sure thing, this should be it: [saveslot0.zip](https://github.com/user-attachments/files/18085160/saveslot0.zip)

Try this. Hasnt been tested outside of this level.

[Nine Sols Ultra-Wide (Steam).zip](https://github.com/user-attachments/files/18087885/Nine.Sols.Ultra-Wide.Steam.zip)
[Nine Sols Ultra-Wide (GamePass).zip](https://github.com/user-attachments/files/18087888/Nine.Sols.Ultra-Wide.GamePass.zip)

**Comment by PGGB** [comment]
Looks good, thanks a lot!
I'll let you know if I run into any further issues or not once I have finished it.
