### ISSUE TITLE
Text looks distorted on 3840x1600

### ISSUE THREAD

**Issue by TerraDK** [p1xel8ted/UltrawideFixes#5]
Works fine with manual install. Running on Full screen at 3840x1600.

Texts (even version # at the bottom) is looking very strange.

![SeaOfStars_TD7lcSp5hI](https://github.com/p1xel8ted/UltrawideFixes/assets/46207023/ea6504c7-7fba-4a28-b475-9a64e60cb888)
![SeaOfStars_1KLyV2Cuoe](https://github.com/p1xel8ted/UltrawideFixes/assets/46207023/2e250986-f463-43ef-a4fd-8539538bb42d)

**Comment by p1xel8ted** [comment]
Please post in referenced issue.
