### ISSUE TITLE
0.1.9 Thread

### ISSUE THREAD

**Issue by p1xel8ted** [p1xel8ted/UltrawideFixes#8]
The filename has changed in 0.1.9 - please ensure you are removing "SeaOfStars.dll" first.
And don't forget to press the star key to reset UI positioning.

**Comment by Bart-90** [comment]
![화면 캡처 2023-09-16 184629](https://github.com/p1xel8ted/UltrawideFixes/assets/15904300/4c6c8823-097f-455f-9712-cc1f21a69d45)
I applied the patch, launched the game, and this is what I see: pixel perfect on & off is same.
My resolution : 3840x1600

**Comment by p1xel8ted** [comment]
> > ![화면 캡처 2023-09-16 184629](https://user-images.githubusercontent.com/15904300/268441352-4c6c8823-097f-455f-9712-cc1f21a69d45.png) I applied the patch, launched the game, and this is what I see: pixel perfect on & off is same. My resolution : 3840x1600
> 
> Exactly the same issue but at 3440x1440. I'm reverting to 0.1.8 for now.

I use 3440x1440, and this is not what I experience. I forgot to mention the filename changed in 0.1.9 - did you remove the old one?

**Comment by Bart-90** [comment]
> > > ![화면 캡처 2023-09-16 184629](https://user-images.githubusercontent.com/15904300/268441352-4c6c8823-097f-455f-9712-cc1f21a69d45.png) I applied the patch, launched the game, and this is what I see: pixel perfect on & off is same. My resolution : 3840x1600
> > 
> > 
> > Exactly the same issue but at 3440x1440. I'm reverting to 0.1.8 for now.
> 
> I use 3440x1440, and this is not what I experience. I forgot to mention the filename changed in 0.1.9 - did you remove the old one (SeaOfStars.dll)?

Yes. SeaOfStars.dll is not in mods folder.

**Comment by p1xel8ted** [comment]
Please delete `MelonPreferences.cfg` in the `Sea of Stars\UserData` folder.

Then try this version:
[SeaOfStars-Ultrawide_v0.1.9.1_ModOnly.zip](https://github.com/p1xel8ted/UltrawideFixes/files/12641355/SeaOfStars-Ultrawide_v0.1.9.1_ModOnly.zip)

**Comment by p1xel8ted** [comment]
> @Bart-90 @pablovesnine

@Bart-90 @pablovesnine

**Comment by level30markus** [comment]
Have the same problem. It works with the mod only. But: Dialogues that should be visible on a black screen (scene change) are now gone. It's the same with version 0.1.8. The only version that works for me is 0.1.7

**Comment by p1xel8ted** [comment]
> Have the same problem. It works with the mod only. But: Dialogues that should be visible on a black screen (scene change) are now gone. It's the same with version 0.1.8. The only version that works for me is 0.1.7

Hi Marcus, what screen resolution are you using and did you reset the UI positioning

**Comment by level30markus** [comment]
> > Have the same problem. It works with the mod only. But: Dialogues that should be visible on a black screen (scene change) are now gone. It's the same with version 0.1.8. The only version that works for me is 0.1.7
> 
> Hi Marcus, what screen resolution are you using and did you reset the UI positioning

3440x1440 and i did the reset with the star key.

**Comment by bigfnj** [comment]
> @Bart-90 @pablovesnine Please delete `MelonPreferences.cfg` in the `Sea of Stars\UserData` folder.
> 
> Then try this version: [SeaOfStars-Ultrawide_v0.1.9.1_ModOnly.zip](https://github.com/p1xel8ted/UltrawideFixes/files/12641355/SeaOfStars-Ultrawide_v0.1.9.1_ModOnly.zip)

This worked for me: 3440x1440 - It corrected the title screen and re-centered the menus. Thanks!

**Comment by level30markus** [comment]
> > Have the same problem. It works with the mod only. But: Dialogues that should be visible on a black screen (scene change) are now gone. It's the same with version 0.1.8. The only version that works for me is 0.1.7
> 
> Hi Marcus, what screen resolution are you using and did you reset the UI positioning

update: i deinstalled sdk and installed the runtime only and reinstalled 01.9.1 now it was possible for me to adjust the UI with +-  the only thing that the star button does is to bring the UI out of sight.
